import { IListing, ListingCategory } from '@/types/listing.interface';

export const DUMMY_LISTINGS: IListing[] = [
  {
    id: '1',
    title: 'Historic Delhi Heritage Walk',
    description: 'Explore the rich history of Old Delhi through its narrow lanes and historic monuments.',
    price: '45.00',
    durationMin: 180,
    meetingPoint: 'Red Fort Gate No. 1',
    maxGroupSize: 10,
    category: ListingCategory.HISTORY,
    active: true,
    city: 'Delhi',
    imageURL: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=1000&auto=format&fit=crop',
    guide: {
      id: 'g1',
      user: {
        id: 'u1',
        name: 'Rahul Sharma',
        profilePicUrl: 'https://i.pravatar.cc/150?u=u1',
      },
    },
  },
  {
    id: '2',
    title: 'Street Food Extravaganza in Mumbai',
    description: 'Tantalize your taste buds with the best street food Mumbai has to offer.',
    price: '30.00',
    durationMin: 120,
    meetingPoint: 'Gateway of India',
    maxGroupSize: 12,
    category: ListingCategory.FOOD,
    active: true,
    city: 'Mumbai',
    imageURL: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1000&auto=format&fit=crop',
    guide: {
      id: 'g2',
      user: {
        id: 'u2',
        name: 'Priya Patel',
        profilePicUrl: 'https://i.pravatar.cc/150?u=u2',
      },
    },
  },
  {
    id: '3',
    title: 'Sunset Photography in Jaipur',
    description: 'Capture the stunning sunset over the Pink City from the best vantage points.',
    price: '55.00',
    durationMin: 150,
    meetingPoint: 'Hawa Mahal Front',
    maxGroupSize: 6,
    category: ListingCategory.PHOTOGRAPHY,
    active: false,
    city: 'Jaipur',
    imageURL: 'https://images.unsplash.com/photo-1477587707331-50da7486f030?q=80&w=1000&auto=format&fit=crop',
    guide: {
      id: 'g3',
      user: {
        id: 'u3',
        name: 'Amit Kumar',
        profilePicUrl: 'https://i.pravatar.cc/150?u=u3',
      },
    },
  },
  {
    id: '4',
    title: 'Goa Nightlife Tour',
    description: 'Discover the hidden gems of Goa nocturnal scene, from beach clubs to secret bars.',
    price: '65.00',
    durationMin: 240,
    meetingPoint: 'Baga Beach Entrance',
    maxGroupSize: 15,
    category: ListingCategory.NIGHTLIFE,
    active: true,
    city: 'Goa',
    imageURL: 'https://images.unsplash.com/photo-1512411411190-7d77bc341772?q=80&w=1000&auto=format&fit=crop',
    guide: {
      id: 'g4',
      user: {
        id: 'u4',
        name: 'Elena DSouza',
        profilePicUrl: 'https://i.pravatar.cc/150?u=u4',
      },
    },
  },
  {
    id: '5',
    title: 'Adventure Trekking in Manali',
    description: 'A moderate trek offering breathtaking views of the Beas River valley.',
    price: '80.00',
    durationMin: 360,
    meetingPoint: 'Old Manali Bridge',
    maxGroupSize: 8,
    category: ListingCategory.ADVENTURE,
    active: true,
    city: 'Manali',
    imageURL: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1000&auto=format&fit=crop',
    guide: {
      id: 'g5',
      user: {
        id: 'u5',
        name: 'Suresh Raina',
        profilePicUrl: 'https://i.pravatar.cc/150?u=u5',
      },
    },
  },
];
